
version: '3.9'

services:
  bot:
    image: 'fominvic81/schedule-bot'
    build: '.'
    container_name: 'schedule-bot'
    restart: always
    environment:
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - .:/app/
    depends_on:
      - database
  database:
    image: 'mongo'
    container_name: 'schedule-bot-db'
    restart: unless-stopped
    command: --port=27017 --replSet=rs0
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db'